server:
  port: 9003

spring:
  application:
    name: permission-service
  datasource:
    url: jdbc:mysql://localhost:3306/java_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver