server:
  port: 9002

spring:
  application:
    name: app-service
  datasource:
    url: jdbc:mysql://localhost:33061/java_test?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
    username: root
    password: test1234
    driver-class-name: com.mysql.cj.jdbc.Driver